### PR TITLE
SBK-16 Fix employees / managers IDs used by tests

### LINKED ISSUE #16: Employee benchmark sometimes assigns an employee as manager of itself
Reproducer:

* Replace `.include( ".*" )` with `.include( ".*update_employeeManager" )` in `org.hibernate.search.benchmark.lucene.PerformanceTestCheckIT`
* Put a breakpoint in `org.hibernate.search.benchmark.model.asset.AutomaticIndexingUpdateSmallPartitionState#updateEmployeeManager` with the condition `managerId == employeeId`
* Launch `org.hibernate.search.benchmark.lucene.PerformanceTestCheckIT` in debug mode

That certainly skews the reindexing performance, so let's make sure the employee is always different from the manager.

Incidentally, if you use `.param( "relationshipSize", "MEDIUM" )` in this same test, you will get an exception at some point because we assume some employee will be a manager, but it's not.

I'm guessing something is wrong in *both* `AutomaticIndexingUpdateMLPartitionState` and `AutomaticIndexingUpdateSmallPartitionState`... I must admit I do not understand the algorithms that select the employee and manager, so maybe @fax4ever could have a look, please?

Note that I recently changed some values in `RelationshipSize.MEDIUM`. That may be the reason for the failure in `AutomaticIndexingUpdateMLPartitionState`, but I would have expected the algorithm to adapt to such change... ?

I would be (very) happy with a solution that involves raising some numbers in `RelationshipSize.SMALL` if it meant merging `AutomaticIndexingUpdateMLPartitionState` with `AutomaticIndexingUpdateSmallPartitionState`...

### PR DESCRIPTION
**Pull request by fax4ever**
Fixes #16

### CODE REVIEW

File: model/src/main/java/org/hibernate/search/benchmark/model/param/RelationshipSize.java [hunk 1]
```diff
@@ -3,7 +3,7 @@
 public enum RelationshipSize {
 
 	SMALL( 1, 1, 1, new int[] { 3 }, 1 ),
```
Comment (yrodiere) [inline model/src/main/java/org/hibernate/search/benchmark/model/param/RelationshipSize.java:5]: As discussed on Zulip, it would be great to change this to use the same algorithm for the small relationship size as for medium/large relationship sizes. We could compensate by reducing the number of companies.

File: model/src/main/java/org/hibernate/search/benchmark/model/asset/AutomaticIndexingUpdateSmallPartitionState.java [hunk 2]
```diff
@@ -11,9 +11,9 @@ public AutomaticIndexingUpdateSmallPartitionState(SessionFactory sessionFactory,
 
 	@Override
 	public void updateEmployeeManager() {
-		int index = ( employeeManagerInvocation / 2 ) % partitionIds.size();
+		int index = ( employeeManagerInvocation ) % partitionIds.size();
 
-		int managerId = partitionId( employeeManagerInvocation );
+		int managerId = partitionId( index );
```
[the remark this answers is not in the document]
Comment (fax4ever) [reply model/src/main/java/org/hibernate/search/benchmark/model/asset/AutomaticIndexingUpdateSmallPartitionState.java:16]: For the small size we have only single-employee companies, so they are all managers.

File: model/src/main/java/org/hibernate/search/benchmark/model/param/RelationshipSize.java (hunk 1 above)
Comment (fax4ever) [reply model/src/main/java/org/hibernate/search/benchmark/model/param/RelationshipSize.java:5]: Yeah, I'm doing that....

**Comment by fax4ever** [comment]
Thanks for the review @yrodiere!
I did some changes.

**Comment by yrodiere** [comment]
Looking good! The problem seems gone.

Merging, thanks.
